import { useState, useRef, useCallback, useEffect } from "react";
import beforeImg from "@/assets/before.webp";
import afterImg from "@/assets/after.webp";

export function StyleSelector() {
  const [sliderPos, setSliderPos] = useState(50);
  const containerRef = useRef<HTMLDivElement>(null);
  const animationRef = useRef<number>(0);
  const directionRef = useRef<1 | -1>(1);
  const isDraggingRef = useRef(false);
  const lastTimeRef = useRef(0);

  const refCallback = useCallback((node: HTMLDivElement | null) => {
    (containerRef as React.MutableRefObject<HTMLDivElement | null>).current = node;
  }, []);

  // Auto-animation
  useEffect(() => {
    const speed = 12;

    const animate = (time: number) => {
      if (lastTimeRef.current === 0) lastTimeRef.current = time;
      const delta = (time - lastTimeRef.current) / 1000;
      lastTimeRef.current = time;

      if (!isDraggingRef.current) {
        setSliderPos((prev) => {
          let next = prev + directionRef.current * speed * delta;
          if (next >= 100) { next = 100; directionRef.current = -1; }
          else if (next <= 0) { next = 0; directionRef.current = 1; }
          return next;
        });
      }

      animationRef.current = requestAnimationFrame(animate);
    };

    animationRef.current = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(animationRef.current);
  }, []);

  // Manual drag
  const getPercent = useCallback((clientX: number) => {
    const rect = containerRef.current?.getBoundingClientRect();
    if (!rect) return 50;
    return Math.max(0, Math.min(100, ((clientX - rect.left) / rect.width) * 100));
  }, []);

  const handlePointerDown = useCallback((e: React.PointerEvent) => {
    isDraggingRef.current = true;
    lastTimeRef.current = 0; // reset so animation resumes smoothly
    const pct = getPercent(e.clientX);
    setSliderPos(pct);
    // Update direction based on current position
    directionRef.current = pct > 50 ? -1 : 1;
    (e.target as HTMLElement).setPointerCapture(e.pointerId);
  }, [getPercent]);

  const handlePointerMove = useCallback((e: React.PointerEvent) => {
    if (!isDraggingRef.current) return;
    const pct = getPercent(e.clientX);
    setSliderPos(pct);
    directionRef.current = pct > 50 ? -1 : 1;
  }, [getPercent]);

  const handlePointerUp = useCallback(() => {
    isDraggingRef.current = false;
    lastTimeRef.current = 0;
  }, []);

  return (
    <div className="rounded-2xl xl:rounded-[32px] border border-border/50 bg-card shadow-soft overflow-hidden h-full">
      <div
        ref={refCallback}
        className="relative w-full h-full overflow-hidden select-none cursor-grab active:cursor-grabbing"
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={handlePointerUp}
        onPointerCancel={handlePointerUp}
      >
        {/* After (cartoon - full background) */}
        <img
          src={afterImg}
          alt="AI Photo to Cartoon result — cartoon-style portrait generated by Rita"
          className="absolute inset-0 w-full h-full block object-cover object-center"
          width="800"
          height="450"
          draggable={false}
        />

        {/* Before (original - clipped) */}
        <div
          className="absolute inset-0 z-[8]"
          style={{ clipPath: `inset(0 ${100 - sliderPos}% 0 0)` }}
        >
          <img
            src={beforeImg}
            alt="Original photo before AI cartoon transformation"
            className="absolute inset-0 w-full h-full block object-cover object-center"
            width="800"
            height="450"
            draggable={false}
          />
        </div>

        {/* Slider handle */}
        <div
          className="absolute z-10 top-0 bottom-0 flex flex-col items-center pointer-events-none"
          style={{ left: `${sliderPos}%`, transform: "translateX(-50%)" }}
        >
          <div className="w-[2px] bg-white flex-1" />
          <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-full border-2 border-white flex items-center justify-center gap-1.5 bg-black/20 backdrop-blur-sm">
            <span className="block h-4 sm:h-5 w-[2px] bg-white rounded-full" />
            <span className="block h-4 sm:h-5 w-[2px] bg-white rounded-full" />
          </div>
          <div className="w-[2px] bg-white flex-1" />
        </div>
      </div>
    </div>
  );
}
